service: solana-eventbridge-lambda

provider:
  name: aws
  stage: dev
  region: us-east-1
  profile: rishi-all-john
  architecture: arm64  # Specify ARM64 architecture for the Lambda function
  ecr:
    images:
      default:
        path: ./  # Path to your Dockerfile
  
functions:
  # Lambda Function Triggered by EventBridge Every Minute
  eventBridgeTrigger:
    timeout: 900
    memorySize: 1024
    image:
      uri: 885181169453.dkr.ecr.us-east-1.amazonaws.com/solana_monitor_lambda:latest
    events:
      - eventBridge:
          schedule: rate(1 minute)  # This triggers Lambda every minute